name: 'GSA/ansible-nessus'
description: 'repository for grace ansible role to install nessus agent'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
    - ansible
contact:
    email: grace-staff@gsa.gov
