---
- name: create {{ redhat_agent_path }} directory
  file:
    path: '{{ redhat_agent_path }}'
    recurse: yes
    state: directory
    mode: '0755'

- name: install nessus agent (redhat)
  yum:
    name: '{{ redhat_nessus_agent_url }}'
    state: present

- name: register nessus agent (redhat)
  command: |
    '{{ redhat_agent_path }}/sbin/nessuscli agent link \
    --key={{ nessus_agent_key }} \
    --host='{{ nessus_server_id }}' \
    --port='{{ nessus_port_id }}''
  args:
    creates: "{{ redhat_agent_path }}/var/nessus/master.key"

- name: start nessus agent
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - nessusagent
