---
- name: install nessus agent (redhat)
  yum:
    name: '{{ redhat_nessus_agent_url }}'
    state: present

- name: check agent link status
  command: '{{ redhat_nessus_agent_path }}/sbin/nessuscli agent status'
  become: yes
  register: nessus_link
  ignore_errors: yes
  changed_when: nessus_link.rc != 0

# adding ignore_errors since this will fail until you have an environment with connectivity to a nessus master host
- name: register nessus agent (redhat)
  command: >
    {{ redhat_nessus_agent_path }}/sbin/nessuscli agent link
    --key={{ nessus_agent_key }}
    --host={{ nessus_server_id }}
    --port={{ nessus_port_id }}
  become: yes
  when: nessus_link is failed
  ignore_errors: yes

# adding ignore_errors since this will fail until you have an environment with connectivity to a nessus master host
- name: start nessus agent
  service:
    name: nessusagent
    enabled: yes
    state: started
  ignore_errors: yes
