---
- name: checking for agent install
  win_stat:
    path: '{{ windows_nessus_agent_path }}'
  register: path

- debug:
    msg: "nessus agent not found"
  when: path.stat.islnk is not defined

- debug:
    msg: "nessus agent found skipping install"
  when: path.stat.islnk is defined

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: create {{ windows_nessus_agent_path }} directory
  win_file:
    path: '{{ windows_nessus_agent_path }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: install nessus agent (windows)
  win_package:
    path: '{{ windows_nessus_agent_url }}'
    log_path: '{{ windows_agent_log }}\\nessus_log.txt'
    product_id: '{{ windows_nessus_product_id }}'
    validate_certs: no
    state: present
    arguments: /qn
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a nessus master host
  when: path.stat.islnk is not defined

- name: link nessus agent (windows)
  win_command: >
    "{{ windows_nessus_agent_path }}\\nessuscli.exe" agent link
    --key={{ nessus_agent_key }}
    --host={{ nessus_server_id }}
    --port={{ nessus_port_id }}
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a nessus master host
  when: path.stat.islnk is not defined

- name: verify nessus started
  win_service:
    name: 'tenable nessus agent'
    state: started
