---
- name: create {{ win_agent_path }} directory
  win_file:
    path: '{{ win_agent_path }}'
    state: directory

- name: create {{ win_agent_logs }} directory
  win_file:
    path: '{{ win_agent_logs }}'
    state: directory

- name: checking for installer
  win_stat:
    path: '{{ win_agent_path }}{{ windows_nessus_agent_filename }}'
  register: installer

- name: move installer to {{ win_agent_path }} directory
  win_copy:
    src: '{{ lin_agent_path }}/{{ item.name }}'
    dest: '{{ win_agent_path }}{{ item.name }}'
  with_items:
    - { name: '{{ windows_nessus_agent_filename }}'}
  when: not installer.stat.exists

- name: install nessus agent (windows)
  win_package:
    path: '{{ win_agent_path }}\\{{ item.name }}'
    chdir: '{{ win_agent_path }}'
    state: present
    log_path: '{{ win_agent_logs }}\\{{ item.name }}_log.txt'
    validate_certs: no
  with_items:
    - { name: '{{ windows_nessus_agent_filename }}' }

- name: link nessus agent (windows)
  win_command: >-
    '{{ win_nessus_path }} agent link --key={{ nessus_agent_key }} --host={{ nessus_server_id }} --port={{ nessus_port_id }}'
