version: 2
jobs:
  ansible_lint:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install ansible-lint
          command: pip install ansible ansible-lint yamllint
      - run:
          name: Show ansible version
          command: ansible --version
      - run:
          name: Syntax check playbook
          command: ansible-playbook --syntax-check tests/test.yml
      - run:
          name: Show ansible-lint version
          command: ansible-lint --version
      - run:
          name: Execute ansible-lint
          command: >
            find . -type f -name '*.yml' | xargs ansible-lint -c .ansible-lint-rules
      - run:
          name: Show yamllint version
          command: yamllint --version
      - run:
          name: Run yamllint
          command: yamllint -s .

workflows:
  version: 2
  lint_and_test:
    jobs:
      - ansible_lint
